import {
  faBook,
  faCalendarDays,
  faChartLine,
  faClipboardList,
  faColumns,
  faDrawPolygon,
  faFolder,
  faGear,
  faHouse,
  faImage,
  faKey,
  faLightbulb,
  faListUl,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faScroll,
  faShieldHalved,
  faSliders,
  faTableCells,
  faTags,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

/** Shared FA icons for shell chrome (Phase 12b). */
export const shellIcons = {
  projects: faTableCells,
  ideas: faLightbulb,
  filesystem: faFolder,
  imageBoard: faImage,
  lists: faListUl,
  calendar: faCalendarDays,
  settings: faGear,
  tasks: faClipboardList,
  kanban: faColumns,
  canvas: faDrawPolygon,
  documents: faBook,
  home: faHouse,
  assistant: faRobot,
  search: faMagnifyingGlass,
  add: faPlus,
  profile: faUser,
  tags: faTags,
  admin: faShieldHalved,
  keys: faKey,
  chart: faChartLine,
  logging: faScroll,
  systemProperties: faSliders,
} as const satisfies Record<string, IconDefinition>;
